# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyChat' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MyChat
  pod 'Masonry'
  pod 'MJRefresh'
  pod 'MJExtension'
  pod 'SDWebImage'
  pod 'AFNetworking'
  pod 'SVProgressHUD'
  target 'MyChatTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyChatUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
